{% set name = "anaconda-client" %}
{% set version = "1.11.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Anaconda-Platform/anaconda-client/archive/{{ version }}.tar.gz
  sha256: 2b3e420e2f52a76796468fb1bf6c3bca4012e4ec111cbdd073d88e8b31def2e5
  patches:
    # Refresh Anaconda.org metadata on new package upload.
    # xref: https://github.com/Anaconda-Platform/anaconda-client/pull/641
    - PR_641.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - anaconda = binstar_client.scripts.cli:main
    - binstar = binstar_client.scripts.cli:main
    - conda-server = binstar_client.scripts.cli:main

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - clyent >=1.2.0
    - conda-package-handling >=1.7.3
    - defusedxml >=0.7.1
    - nbformat >=4.4.0
    - python-dateutil >=2.6.1
    - pytz >=2021.3
    - pyyaml >=3.12
    - requests >=2.20.0
    - setuptools >=58.0.4
    - six >=1.15.0
    - tqdm >=4.56.0
    - urllib3 >=1.26.4
    - anaconda-project >=0.9.1
    - pillow >=8.2

test:
  imports:
    - binstar_client
    - binstar_client.commands
    - binstar_client.inspect_package
    - binstar_client.mixins
    - binstar_client.scripts
    - binstar_client.utils
    - binstar_client.utils.notebook

  commands:
    - anaconda --help
    - binstar --help
    - conda-server --help

about:
  home: https://github.com/Anaconda-Platform/anaconda-client
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: Anaconda Cloud command line client library
  doc_url: https://docs.anaconda.com/anaconda-cloud/user-guide/getting-started/
  dev_url: https://github.com/Anaconda-Platform/anaconda-client

extra:
  recipe-maintainers:
    - jakirkham
    - goanpeca
    - beckermr
