{% set version = "1.14.0" %}

package:
  name: anaconda-client
  version: {{ version }}

source:
  url: https://github.com/Anaconda-Platform/anaconda-client/archive/{{ version }}.tar.gz
  sha256: 2f3f26bff6753d5a55bc21736626080613a34848a1f4072afad5f56775a2bd85

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-build-isolation --no-deps . -vv
  entry_points:
    - binstar = binstar_client.scripts.cli:main
    - conda-server = binstar_client.scripts.cli:main

requirements:
  host:
    - pip
    - python
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - hatch-requirements-txt
  run:
    # Based on:
    # requirements.txt, conda.recipe/meta.yaml, requirements-extra.txt
    - python
    - anaconda-anon-usage >=0.7.3
    - anaconda-cli-base >=0.5.3
    - anaconda-auth >=0.11.0 # minimum effectively required
    - conda-package-handling >=1.7.3
    - defusedxml >=0.7.1
    - nbformat >=4.4.0
    - platformdirs >=3.10.0,<5.0
    - python-dateutil >=2.6.1
    - pytz >=2021.3
    - pyyaml >=3.12
    - requests >=2.20.0
    - requests-toolbelt >=0.9.1
    - setuptools >=58.0.4
    - tqdm >=4.56.0
    - urllib3 >=1.26.4
  run_constrained:
    - anaconda-project >=0.9.1
    - pillow >=8.2

test:
  imports:
    - binstar_client
    - binstar_client.commands
    - binstar_client.inspect_package
    - binstar_client.mixins
    - binstar_client.scripts
    - binstar_client.utils
    - binstar_client.utils.notebook
  source_files:
    - tests
  requires:
    - conda
    - pip
    - pytest >=8.4
    - pytest-mock >=3.15
    - pillow
    - freezegun >=1.5
  commands:
    - pip check
    - export ANACONDA_CLI_FORCE_NEW=1  # [unix]
    - set ANACONDA_CLI_FORCE_NEW=1     # [win]
    - anaconda -h
    - anaconda -V
    - anaconda org --help
    - python -c "import binstar_client; print(f'binstar_client.__version__ is {binstar_client.__version__}')"
    - python -c "import binstar_client; assert binstar_client.__version__ == \"{{ version }}\""
    - pytest -v tests

about:
  home: https://anaconda.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: anaconda.org command line client library
  description: |
    Anaconda-client is used to connect to and manage your Anaconda Cloud account, upload packages you have created
    and generate access tokens to allow access to private packages.
  doc_url: https://docs.anaconda.com/anacondaorg/
  doc_source_url: https://github.com/anaconda/anaconda-client/blob/master/README.md
  dev_url: https://github.com/anaconda/anaconda-client
