# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.13.0

package:
  name: anaconda-client
  version: ${{ version }}

source:
  url: https://github.com/anaconda/anaconda-client/archive/${{ version }}.tar.gz
  sha256: e1dcefb66a09e99278c2dcf21ae41bc1328c0dbb762025a20f36e4e9fcf8d593

build:
  number: 1
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed --disable-pip-version-check
  python:
    entry_points:
      - binstar = binstar_client.scripts.cli:main
      - conda-server = binstar_client.scripts.cli:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - anaconda-cli-base >=0.4.0
    - conda-package-handling >=1.7.3
    - conda-package-streaming >=0.9.0
    - defusedxml >=0.7.1
    - nbformat >=4.4.0
    - platformdirs >=3.10.0,<5.0
    - python >=${{ python_min }}
    - python-dateutil >=2.6.1
    - pytz >=2021.3
    - pyyaml >=3.12
    - requests >=2.20.0
    - requests-toolbelt >=0.9.1
    - setuptools >=58.0.4
    - tqdm >=4.56.0
    - urllib3 >=1.26.4
    # Technically an `[extra]`, but fails to upload on any `icon`
    # https://github.com/conda-forge/anaconda-client-feedstock/issues/57
    - pillow >=8.2

tests:
  - python:
      python_version: ${{ python_min }}.*
      pip_check: true
      imports:
        - binstar_client
        - binstar_client.commands
        - binstar_client.inspect_package
        - binstar_client.mixins
        - binstar_client.scripts
        - binstar_client.utils
        - binstar_client.utils.notebook
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - binstar --help
      - conda-server --help
      - python -c "from binstar_client.utils.notebook.data_uri import DataURIConverter; DataURIConverter(None).check_pillow_installed()"

about:
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: anaconda.org command line client library
  homepage: https://github.com/anaconda/anaconda-client
  repository: https://github.com/anaconda/anaconda-client
  documentation: https://www.anaconda.com/docs/tools/anaconda-org/commandreference

extra:
  recipe-maintainers:
    - jakirkham
    - goanpeca
    - mbargull
    - mattkram
